title        = "kogakure.de - Ninja, Ninjutsu und Kampfkunst"
baseURL      = "http://0.0.0.0:8888/"
languageCode = "de"

metaDataFormat  = "yaml"
paginate        = 0
buildDrafts     = true
buildFuture     = true
disableKinds    = ["404"]
enableRobotsTXT = true
watch           = true

archetypedir = "app/archetypes"
contentdir   = "app/content"
dataDir      = "app/data"
layoutdir    = "app/layouts"
staticdir    = "app/static"
themesdir    = "app/themes"
publishdir   = "dist"

[blackfriday]
smartypants     = false
plainIDAnchors  = true
hrefTargetBlank = true
extensions      = [""]

[permalinks]
artikel = "/artikel/:slug/"

[params]
tracking = false
