[build]
  command = "yarn run build"
  publish = "dist"

[build.environment]
  HUGO_VERSION = "0.26"

[context.production.environment]
  HUGO_VERSION = "0.26"

[context.deploy-preview]
  command = "yarn run build-preview"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.26"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.26"
